CREATE TABLE products (
  id VARCHAR(255) PRIMARY KEY ,
  name VARCHAR(255) NOT NULL ,
  description VARCHAR(255) NOT NULL ,
  price DOUBLE NOT NULL
);

CREATE TABLE users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL
);
